---
name: 'Scim2'
configurationClass:
  name: 'Scim2Configuration'
  package: 'com.exclamationlabs.connid.base.scim2.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  authenticator:
    oauth2ClientCredentials: true
custom:
  items:
    required:
      scim2UserUrl:
        type: string
        order: 701
        display: 'Service Provider URL'
        help: 'Service Provider URL to Connect'
      configUser:
        type: string
        order: 710
        display: 'Configuration Data Location'
        help: 'Path to Configuration file (For Service Providers like AWS)'
      boolConfigUser:
        type: boolean
        default: 'false'
        order: 720
        display: 'what is this'
        help: 'Need to explore'
      scim2GroupUrl:
        type: string
        order: 730
        display: 'Service Provider URL'
        help: 'Service Provider URL to Connect'
      configGroup:
        type: string
        order: 740
        display: 'Configuration Data Location'
        help: 'Path to Configuration file (For Service Providers like AWS)'
      boolConfigGroup:
        type: boolean
        default: 'false'
        order: 750
        display: 'what is this'
        help: 'Need to explore'