---
name: 'Scim2'
configurationClass:
  name: 'Scim2Configuration'
  package: 'com.exclamationlabs.connid.base.scim2.configuration'
rest: true # io-error-retries
service: true # service-url
results: true
security:
  authenticator:
    oauth2ClientCredentials: true
custom:
  items:
    required:
      schemaUrl:
        type: string
        order: 701
        display: 'Schema URL'
        help: 'Schema URL to Connect'
      schemaRawJson:
        type: string
        order: 710
        display: 'Schema Raw JSON'
        help: 'Raw JSON'
      useSchemaUrl:
        type: boolean
        default: 'false'
        order: 720
        display: 'Use Schema URL'
        help: 'Choose True to use Schema URL, otherwise Midpoint uses Schema raw JSON'
      resourceTypeUrl:
        type: string
        order: 730
        display: 'Resource Type URL'
        help: 'Resource Type URL to Connect'
      resourceTypeRawJson:
        type: string
        order: 740
        display: 'Resource Type Raw JSON'
        help: 'Resource Type Raw JSON'
      useResourceTypeUrl:
        type: boolean
        default: 'false'
        order: 750
        display: 'Use Resource Type URL'
        help: 'Choose True to use Resource Type URL, otherwise Midpoint uses Resource Type raw JSON'
      standardUser:
        type: boolean
        default: 'true'
        order: 760
        display: 'Standard User'
        help: 'Choose True '
      enterpriseUser:
        type: boolean
        default: 'false'
        order: 770
        display: 'Enterprise User'
        help: 'Choose True to add Enterprise User Privileges to the User'
